<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function simple_oauth_password_grant_form_consumer_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['default_scopes'] = [
    '#type' => 'details',
    '#title' => new TranslatableMarkup('Default scopes'),
    '#open' => TRUE,
    '#weight' => 2,
    'scopes' => $form['client_credentials']['scopes'],
  ];

  unset($form['client_credentials']['scopes']);
}
