name: Lint & Test

on:
  - push
  - pull_request
  - pull_request_target

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - drupal: "10"
            php: "8.2"
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            /tmp/composer-cache
            ./web
            ./vendor
            ./composer.spoons.json
            ./composer.spoons.lock
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}-php${{ matrix.php }}-drupal${{ matrix.drupal }}

      - name: Install drupal
        uses: wunderwerkio/github-action-composer@v1-beta
        with:
          php_version: ${{ matrix.php }}
          setup_drupal: yes
          drupal_core_constraint: "^${{ matrix.drupal }}"

      - name: Lint
        uses: wunderwerkio/github-action-composer@v1-beta
        with:
          php_version: ${{ matrix.php }}
          command: phpcs
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - drupal: "9"
            php: "8.0"
          - drupal: "9"
            php: "8.1"
          - drupal: "10"
            php: "8.1"
          - drupal: "10"
            php: "8.2"
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            /tmp/composer-cache
            ./web
            ./vendor
            ./composer.spoons.json
            ./composer.spoons.lock
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}-php${{ matrix.php }}-drupal${{ matrix.drupal }}

      - name: Install drupal
        uses: wunderwerkio/github-action-composer@v1-beta
        with:
          php_version: ${{ matrix.php }}
          setup_drupal: yes
          drupal_core_constraint: "^${{ matrix.drupal }}"

      - name: Test
        uses: wunderwerkio/github-action-composer@v1-beta
        with:
          php_version: ${{ matrix.php }}
          command: unit
